[tasks.build]
run = [
    "podman build -t ghcr.io/atty303/arch-toolbox-paru:latest arch-toolbox-paru",
    "podman build -t ghcr.io/atty303/arch-dms:latest arch-dms",
    "podman build -t ghcr.io/atty303/arch-scroll:latest arch-scroll",
]
