name: Check images

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          install: true
          cache: true
      - run: mise run check

  images:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 2
      - uses: jdx/mise-action@5228313ee0372e111a38da051671ca30fc5a96db # v3
        with:
          install: true
          cache: true
      - run: sudo apt-get update && sudo apt-get install --yes podman distrobox
      - name: Build fixed images and test reference Distroboxes
        run: |
          mise run test:images
          mise run test:distrobox
