ARG BASE_IMAGE=quay.io/toolbx/arch-toolbox@sha256:6ec5035d4038d6dbec37ce67891e9fc2e0dfa6566fa9635a61e281115ef5c295
FROM ${BASE_IMAGE}
ARG ARCH_SNAPSHOT
ARG PARU_VERSION
ARG PARU_COMMIT
COPY common/arch /tmp/common-arch
RUN chmod 0755 /tmp/common-arch/provision.sh && /tmp/common-arch/provision.sh && \
    pacman -S --needed --noconfirm rust && \
    for attempt in 1 2 3; do \
      if sudo -H -u builder git clone https://github.com/Morganamilo/paru.git /var/build/paru; then break; fi; \
      rm -rf /var/build/paru; test "${attempt}" -lt 3 || exit 1; sleep "${attempt}"; \
    done && \
    sudo -H -u builder git -C /var/build/paru checkout --detach "${PARU_COMMIT}" && \
    sudo -H -u builder bash -lc 'cd /var/build/paru && cargo build --locked --release' && \
    install -Dm0755 /var/build/paru/target/release/paru /usr/bin/paru && \
    install -Dm0644 /var/build/paru/paru.conf /etc/paru.conf && \
    install -Dm0644 /var/build/paru/man/paru.8 /usr/share/man/man8/paru.8 && \
    install -Dm0644 /var/build/paru/man/paru.conf.5 /usr/share/man/man5/paru.conf.5 && \
    rm -rf /var/build/paru /tmp/common-arch
LABEL io.atty303.distrobox.paru-version="${PARU_VERSION}" \
      io.atty303.distrobox.paru-commit="${PARU_COMMIT}" \
      io.atty303.distrobox.arch-snapshot="${ARCH_SNAPSHOT}"
ENTRYPOINT []
