FROM quay.io/toolbx/arch-toolbox:latest

# makepkg cannot be executed as root, so add a regular user for building
RUN useradd builder -m && echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

# Install paru to enable AUR repository usage
RUN sudo -H -u builder sh -c "cd && rm -rf paru && git clone https://aur.archlinux.org/paru.git paru && cd paru && makepkg -si --noconfirm"
